# eqn: x 3 * sin x 0.005 * cos +
init: x 1 *  
seed: 42
seq_len: 12
_iter: 2000

## max seq len 12
# PDE: q psi jacobian neg q lap 0.01 x * * + 
# PDE_init: q 
# finds q neg q invlap jacobian

# PDE: q psi jacobian neg 0.01 * q lap x * + 
# PDE_init: q 
# finds q lap x *

# PDE: q psi jacobian neg 0.9 * q lap x * + 
# PDE_init: q 
# finds q lap x *